server:
  port: 8080

spring:
  resources:
    static-locations: classpath:/static/,file:${user.dir}/static/img/
  mvc:
    static-path-pattern: /static/**

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    # 禁用生产环境中的 DevTools
    active: dev

  thymeleaf:
    # 模板文件的前缀，默认是 `classpath:/templates/`
    prefix: classpath:/templates/
    # 模板文件的后缀，默认是 `.html`
    suffix: .html
    # 是否启用缓存。开发环境中建议关闭，生产环境中建议开启
    cache: false
    # 是否启用模板解析，默认为 true
    enabled: true
    # 模板编码，默认为 UTF-8
    encoding: UTF-8
    # 内容类型，默认为 text/html
    content-type: text/html
    # 模板模式，默认为 HTML5
    mode: HTML5

  mail:
    host: smtp.163.com
    username: "wangjiajin0920@163.com"  # 从环境变量中读取
    password: "STTFWKSLJHEIMBPC"  # 从环境变量中读取
    properties:
      mail:
        smtp:
          ssl:
            enable: true  # 启用 SSL 加密
    default-encoding: UTF-8

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration: DEBUG
    # 如果生产环境需要关闭日志，请调整为 INFO 或 WARN
    # level:
    #   org.springframework.web: INFO

  datasource:
    url: jdbc:mysql://123.60.90.253:3306/huaban?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: huaban
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5               # 初始连接数
    min-idle: 5                  # 最小空闲连接数
    max-active: 50               # 最大活动连接数
    max-wait: 5000               # 获取连接的最大等待时间，单位毫秒
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: true         # 每次借用连接时验证连接是否有效
    test-while-idle: true        # 连接空闲时是否检查连接有效性
    time-between-eviction-runs-millis: 30000  # 空闲连接回收时间，单位毫秒
    min-evictable-idle-time-millis: 30000     # 空闲连接的最小回收时间，单位毫秒
    remove-abandoned: true       # 启用连接超时回收
    remove-abandoned-timeout: 300 # 超过300秒未使用的连接会被回收
    log-abandoned: true          # 打印被回收的连接信息
    max-conn-lifetime: 300000    # 单个连接最大生命周期，单位毫秒（5分钟）

    # 确保每个连接结束后自动提交并回收
    auto-commit: true            # 确保每次数据库操作后自动提交

    # 配置事务管理器
  transaction:
    manager:
      enabled: true # 启用事务管理器

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true  # 自动映射下划线命名
    logging:
     level:
      com.alibaba.druid.pool: DEBUG  # 打印 Druid 连接池的调试日志



  # Swagger 配置
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
      version: 1.0
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'cf'
        paths-to-match: '/**'
        packages-to-scan: com.cf.huaban.controller

